name: import-cinehub-visuals

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  import:
    if: github.event.head_commit.message != 'chore(repo): import CineHUB visuals'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download CineHUB visuals
        shell: bash
        run: |
          set -e
          mkdir -p assets/cinehub/{logos,banners,screenshots}
          curl -fL --retry 3 'https://uc42dc25620d0e1528f9b50ec8b7.dl.dropboxusercontent.com/cd/0/get/DJYcghq-GkgUuE7Rjl2JQgk6cSiOoFMwDMZyYMV1lCJ0WuEFp-6uX29iuX5x3cYi_6xGyuv8RkSIyE0L5CplB6osuZH2evQheYhlYUjiOq7bsBPGFqbqsKFiBoz_d31JSpx5nbVlvE5vUnRNOz8JwrWhTAPsKXC-xhnZ4bMi2oUEmw/file?c_luid=d5ec18f9' -o assets/cinehub/logos/logo-horizontal.png
          curl -fL --retry 3 'https://uca70acac1cab4889029e5f68cb7.dl.dropboxusercontent.com/cd/0/get/DJZxn_j4Is-o-XLHo1GYsuflHHssdM3VfbWQTzqbZKKO2Glk5f_5aW5017MJarS9b47pJG73TH36JaiGciKxPtO4fZXEDo3gFJqTYF_7IBvTE5Blnw9-F0Y2al3o4jrZw4PYzLabnUtc80UNgG-HYQWxgEYxkPIc99FzG5mSRPyQzg/file?c_luid=d5ec18f9' -o assets/cinehub/logos/logo-vertical.png
          curl -fL --retry 3 'https://uc7fc3c28eef5558a5750827d21b.dl.dropboxusercontent.com/cd/0/get/DJZmISoHNNUb8iZhfDI3Me_ebGxGCMb2EimTtJ4RENXRZCiA3_k4bzFCPv56UWEUm3_5nq5pGHMEfwUTBrvgTCrZS9mvbhyylJ3Cip1SfAltsS9S7Zs5fV4GQRjyUjlJ7zc2YUKG55q665_W2IIpYfBBMhGKx7ELR0c5KDjCbIPAKw/file?c_luid=d5ec18f9' -o assets/cinehub/logos/icon-512.png
          curl -fL --retry 3 'https://uc88b4691b87a62c5474e5afdea4.dl.dropboxusercontent.com/cd/0/get/DJaNBbnh2uH5OL9HiKmbe64aQlmI_rOhhtqrQwngvfSK0vdv1LlVo1PyMiJhXBQ4Jak3YOAKtqDX6OqG4knI0_1tBoJY47dpJIAvhg66spnnVW001ITL02PEvop0xvaVUERS90YOs13xAM33_sjR8uNdva0yDScxoP0qAxJg7ArZHQ/file?c_luid=d5ec18f9' -o assets/cinehub/banners/cinehub-entretenimento.png
          curl -fL --retry 3 'https://uc829c5c672dd7a8014b69fa8f31.dl.dropboxusercontent.com/cd/0/get/DJahl_tQ3lHZmD24mtNmCNzITBoMBMI7QucUzUWsibhCI0uCr020CQC4rdlu67ypaGYfxmUH5WBmiYrbMeAv6CL_vALWkgE_K4jkJEhvVKEzKjRbNOanZZLABZtJckiI_LSVcLPlc0zhy56bb4FBwIQhzSeEvKuKiwfcZp-1RZmxDA/file?c_luid=d5ec18f9' -o assets/cinehub/banners/cinehub-banner-2.png
          curl -fL --retry 3 'https://uc72256d5302164d682bb842b14f.dl.dropboxusercontent.com/cd/0/get/DJaVsZbqoBnoBf47jbNYeyA8OLR58cddTz_OugRfpYcNEbhrYT-ETGHLdosj5eLnFCXRxt0zSMjjJF15pMzX8jPdJUVBS1E29cB9skonGp012OkWPyKDtcJL_lM-VsYw_atYtUCt4KPR_gUCJBT9RX8_B-bMB-xMLhysTZtMIp3ZFw/file?c_luid=d5ec18f9' -o assets/cinehub/screenshots/home-01.png
          curl -fL --retry 3 'https://ucc00752a84181fbf95e501129ff.dl.dropboxusercontent.com/cd/0/get/DJa3eZe5GEJ4ph7MDBd6d05r1Z7rarMQ9kP5NUHm-aWTwX0xF27eBsj9r7mwTXnYOdD8yKxz13qqQwgoXioBTn76orPX4e3WRfed2DbMdG0JWsjW_QXWb8Bp3C1pu2z70sWOMvt58LHKM4swW-0Yyv1tKL9_nOdivJE_OAHV8CnMGQ/file?c_luid=d5ec18f9' -o assets/cinehub/screenshots/home-02.png
          curl -fL --retry 3 'https://ucf948739eaecd7bc927c67d04e7.dl.dropboxusercontent.com/cd/0/get/DJZLcZyF8vbqB_vGGQOBbRGy48wzMMT_sXKqJIWI4ZyRbp_bPrDhCS6Xc6IqLcVmVMuojTFhFAyZ0a_-uXOuUbn2TsY9go4LAg7mgVMWUAw6g4dSWpNjYsT2B-dG7jtvsVp26QgeEOyIzzU8BRy16CStt-6-MWy-z4MoozoUhle7qg/file?c_luid=d5ec18f9' -o assets/cinehub/screenshots/home-03.png
          curl -fL --retry 3 'https://ucede290f3bcd4dc3ce9b43dd003.dl.dropboxusercontent.com/cd/0/get/DJYAgRYbf1bOQclritLvnu69v5HRnVsRwEexTpFh8cyR3hWB2WUaHubUq4on5VNbKQXPCW2e6LdqfD5YLCmfPKdncl-3lHeavopd_Ef_KeUBZIdLSdxLdbN0yNaCUVwxcZ_d312JusTtT_Nhw8sErVFu7KbSJy7ttDXlJC7KMLTaug/file?c_luid=d5ec18f9' -o assets/cinehub/screenshots/home-04.jpg
          curl -fL --retry 3 'https://ucd116fd250429c3be649ce320fc.dl.dropboxusercontent.com/cd/0/get/DJae3f_YhYGZHjnMbdsdCZNGgduk5N3zH-G-iC9mbqIVS_g5mbxzU8N3EjUELQXaqQrA4uaS4OtSkAdNm-rX-HL-_PVchqrsMsTB5he_n7RzIfqNHdIlj8_p8nB8PRO22vUVn6m-KQZauADE5t-ZE_hc3lJPM6My3tGQ879oiCzpMg/file?c_luid=d5ec18f9' -o assets/cinehub/screenshots/home-05.png
          file assets/cinehub/logos/* assets/cinehub/banners/* assets/cinehub/screenshots/*
      - name: Commit visuals
        shell: bash
        run: |
          git config user.name "CineHUB Bot"
          git config user.email "actions@users.noreply.github.com"
          git add assets/cinehub
          git commit -m "chore(repo): import CineHUB visuals"
          git push
